# Generated by Django 4.1.3 on 2022-11-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_image_id_alter_image_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload',
            new_name='image',
        ),
    ]
