# Generated by Django 4.1.3 on 2022-11-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='sort',
        ),
    ]
