# Generated by Django 4.1.3 on 2022-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_options_remove_image_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_id']},
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
